---
title: "Report"
author: "Fabio A Oliveira"
date: "8/1/2020"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# TLDR
#### (_Too Long, Didn't Read or the contents of your typical README.md file_)


# Introduction

## Instructions

This analysis proposes 2 different algos to identify prominent features in stock data  

If you want to replicate the analysis, clone the repository  

The files do ABC, the folder contains XYZ  

This file contains images but github does not render gifs. You can continue reading with static images or go to link to see cool visualizations (pensar em colocar link para os gifs rodando direto no browser, ou então criar logo um blog com wordpress e hospedar o artigo)  

GITHUB NÃO RENDERIZA IMAGENS! TEM QUE COLOCAR O LINK DA IMAGEM, MAS ELE NÃO CRIA PELO CÓDIGO R NO MARKDOWN. CARREGAR DESTA MANEIRA NESTE REPORT E CORRIGIR O REPORT DE GENDER BIAS

## The idea

Motivation:  
Identify prominent features in a time series  
Motivated by analysis of stock market  
Difficulty in defining explicit buy/sell strategies from raw data, too noisy and patterns are difficult to identify

3 hypothesis (yet to be confirmed):
* __Easier to identify relationships:__ stocks from the same sector etc
* __More efficient trend identification:__ less noise, bare essentials and prominent features, algo needs to predict next point, good enough info for buy/sell decisions, closer to features humans identify and more related to fundamentalist analysis
* __Evidences market volatility:__ histogram with point density shows periods of intense volatility

# The algos

## Recursive algo

* 1st version: recursive - features:, limitations:, gif .. 

* Recursive algo:
1. Define interval under analysis as the full interval between first and last available points
2. Draw reference line segment between the two points
3. Evaluate deviation between all the values in the segment and the reference line
4. If any point deviates more than the tolerance, the point where the highest deviation is found will be defined as a pivot point
5. For each new pivot point added, run steps 2-4 to recursively evaluate the two segments defined by cutting the interval defined in step 1 at the new pivot point  

## Sequential algo

* 2nd version: sequential - features:, limitations, gif:..

* Sequential algo:  
1. Define interval under analysis (will begin at last pivot point and end at current value, if there is no last point, will use the first point in the time series)
2. Draw reference line segment between the two points
3. Evaluate deviation between all the values in the segment and the reference line
4. If any point deviates more than the tolerance, the point where the highest deviation is found will be defined as a pivot point
5. For each new value, repeat steps 1-4

ilustrar com 2 gifs:  
* escala estática, ação inteira já mostrada, pontos calculados valor a valor (como se estivesse analisando uma ação já disponível)
* escala móvel, gif infinito, ilustrando o funcionamento com novos pontos chegando

# Next steps

* Run on full or significant portion of stock market history
* Attempt to identify patterns in volatility and link to significant events
* Attempt to cluster different stocks into sectors by finding correlations
* Attempt to predict next pivot points from historical data (train with all, predict with one stock combination of pivot points for index & pivot points for sector)
* Share functions as package